name: Website Deployment

on:
  push:
    branches:
    - main

jobs:
  S3-terraform:
    uses: ./.github/workflows/s3-terraform.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    with:
      aws_region: ${{ vars.AWS_REGION }}
      bucket_name: ${{ vars.BUCKET_NAME }}

  S3-static-site:
    needs: [S3-terraform]
    uses: ./.github/workflows/static-site.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    with:
      bucket_name: ${{ needs.S3-terraform.outputs.bucket_name }}
      aws_region: ${{ vars.AWS_REGION }}

  Route-53:
    needs: [S3-terraform, S3-static-site]
    uses: ./.github/workflows/dns-terraform.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    with:
      aws_region: ${{ vars.AWS_REGION }}
      domain_name: ${{ vars.DOMAIN_NAME }}
      bucket_name: ${{ needs.S3-terraform.outputs.bucket_name }}
      cloudfront_domain_name: ${{ needs.S3-terraform.outputs.cloudfront_domain_name }}
      cloudfront_zone_id: ${{ needs.S3-terraform.outputs.cloudfront_zone_id }}











