name: "S3Terraform Plan/Apply"

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      bucket_name:
        required: true
        type: string
    outputs:
      bucket_name:
        description: "The name of the created bucket"
        value: ${{ jobs.terraform-apply.outputs.bucket_name }}
      bucket_hosted_zone_id:
        description: "The hosted zone ID for the bucket"
        value: ${{ jobs.terraform-apply.outputs.bucket_hosted_zone_id }}
      cloudfront_domain_name:
        description: "The domain name for the cloudfront distribution"
        value: ${{ jobs.terraform-apply.outputs.cloudfront_domain_name }}
      cloudfront_zone_id:
        description: "The hosted zone for the cloudfront distribution"
        value: ${{ jobs.terraform-apply.outputs.cloudfront_zone_id }}

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.tfplanExitCode }}

    steps:
      # Checkout the repo to the runner
      - name: Checkout
        uses: actions/checkout@v4

      #  Install the latest Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      # Assume AWS Role
      - name: AWS Assume
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GH-AWS-OIDC
          aws-region: ${{ inputs.aws_region }}

      # Initialize Terraform and remote state
      - name: Terraform Init
        run: |
          terraform init \
          -backend-config=region=${{ secrets.AWS_REGION }} \
          -backend-config=bucket=${{ secrets.AWS_S3_BUCKET }} \
          -backend-config=key="jslsn/just-listen-site/s3/terraform.tfstate" \
          -backend-config=dynamodb_table=${{ secrets.AWS_DDB }} \
          -backend-config=encrypt=true
        working-directory: terraform/deployments/bucket

      # Execution plan for Terraform
      - name: Terraform Plan
        id: tf-plan
        run: |
          export exitcode=0
          terraform plan -detailed-exitcode -no-color -out tfplan \
          -var="aws_region=${{ inputs.aws_region }}" \
          -var="certificate_arn=${{ secrets.ACM_ARN }}" \
          -var="bucket_name=${{ inputs.bucket_name }}" || export exitcode=$?
          
          echo "tfplanExitCode=$exitcode" >> $GITHUB_OUTPUT
        working-directory: terraform/deployments/bucket

      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: s3-tfplan
          path: terraform/deployments/bucket/tfplan

  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    if: needs.terraform-plan.outputs.tfplanExitCode == '2'
    needs: [terraform-plan]
    outputs:
      bucket_regional_domain_name: ${{ steps.tf-output.outputs.bucket_regional_domain_name }}
      bucket_hosted_zone_id: ${{ steps.tf-output.outputs.bucket_hosted_zone_id }}
      bucket_name: ${{ steps.tf-output.outputs.bucket_name }}

    steps:
      # Checkout the repo to the runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Assume AWS Role
      - name: AWS Assume
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GH-AWS-OIDC
          aws-region: ${{ inputs.aws_region }}

      # Initialize Terraform and remote state
      - name: Terraform Init
        run: |
          terraform init \
          -backend-config=region=${{ secrets.AWS_REGION }} \
          -backend-config=bucket=${{ secrets.AWS_S3_BUCKET }} \
          -backend-config=key="jslsn/just-listen-site/s3/terraform.tfstate" \
          -backend-config=dynamodb_table=${{ secrets.AWS_DDB }} \
          -backend-config=encrypt=true
        working-directory: terraform/deployments/bucket

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: s3-tfplan
          path: terraform/deployments/bucket

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/deployments/bucket

      - name: Get Terraform Outputs
        id: tf-output
        run: |
          echo "bucket_name=$(terraform output -raw bucket_name)" >> $GITHUB_OUTPUT
          echo "bucket_hosted_zone_id=$(terraform output -raw bucket_hosted_zone_id)" >> $GITHUB_OUTPUT
          echo "cloudfront_domain_name=$(terraform output -raw cloudfront_domain_name)" >> $GITHUB_OUTPUT
          echo "cloudfront_zone_id=$(terraform output -raw cloudfront_zone_id)" >> $GITHUB_OUTPUT
        working-directory: terraform/deployments/bucket

